version: '3'

services:

 chrome:

  build:

   context: .

   dockerfile: Dockerfile

  command: "--browser chrome"

  volumes:

   - ./cypress:/cypress

   - ./cypress.json:/cypress.json

   - ./package.json:/package.json

   - ./cucumber_report/chrome:/cucumber_report

 firefox:

  build:

   context: .

   dockerfile: Dockerfile

  command: "--browser firefox --config video=false"

  environment:

   - DEBUG=cypress:server:browsers:firefox-util

  volumes:

   - ./cypress:/cypress

   - ./cypress.json:/cypress.json

   - ./package.json:/package.json

   - ./cucumber_report/firefox:/cucumber_report